# 기본 Jekyll 설정
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "mint"

# 사이트 정보
title: "개발 블로그"
name: "devkdb"
description: "나의 개발 블로그"
url: "https://devkdb.github.io"
baseurl: ""

# 포스트 설정
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# 기본 레이아웃 설정
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Jekyll 플러그인
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Markdown 설정
markdown: kramdown
highlighter: rouge

# Pagination 설정
paginate: 5
paginate_path: "/page:num/"

# 빌드 오류 방지
future: true
