# Jekyll 테마 설정
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "mint"

# 사이트 정보
title: "개발 블로그"
name: "devkdb"
description: "나의 개발 블로그"
url: "https://devkdb.github.io"
baseurl: ""  # GitHub Pages 저장소가 username.github.io 라면 baseurl이 빈 값이어야 함.

# 포스트 관련 설정
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# 기본 설정
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Pagination 설정
paginate: 5
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
